name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install Dependencies
      - name: Install Dependencies
        run: |
          cd backend
          npm install
          cd ../frontend
          npm install

      # Build Frontend
      - name: Build Frontend
        run: |
          cd frontend
          CI=false npm run build

      # Deploy to Server
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: 46.101.154.184
          USER: root
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh -i private_key.pem -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            cd /var/www/jps_erp_node
            git pull origin main
            cd backend && npm install && pm2 restart all
            cd ../frontend && npm run build
            sudo systemctl restart nginx
          EOF